### ISSUE TITLE
Another Awesome Ipsum List

### ISSUE THREAD

**Issue by aharris88** [templeman/awesome-ipsum#12]
I have an awesome ipsum list [here](https://github.com/aharris88/awesome-ipsum). Your list is more comprehensive, so I'm probably just going to link to yours and close mine out, but if there's anything on my list that you don't have, feel free to add it to your list.

**Comment by waldyrious** [comment]
According to the always extremely useful [Venny](http://bioinfogp.cnb.csic.es/tools/venny/) list comparison tool, there are apparently 4 links in @aharris88's list that aren't present in @templeman's:

- http://adhesiontext.com
- http://randomtext.me
- http://liquoripsum.com
- http://fillerama.io

And also these tools:
- [Emmet](http://docs.emmet.io/abbreviations/lorem-ipsum/) - a plugin avaliable for [all these editors](http://emmet.io/download/).
- [Placeholders for Sublime Text](https://github.com/mrmartineau/Placeholders) - Placeholder HTML & content (lorem ipsum) package for Sublime Text.

I might have missed something, but this is a start :)

**Comment by aharris88** [comment]
And it looks like http://liquoripsum.com/ is down.

**Comment by templeman** [comment]
Thanks again @aharris88 for sharing your list! I did a pass to bring over any items that you have listed that I was missing (thanks for your help @waldyrious).
