### ISSUE TITLE
Dead "Duck Island Greeking Machine" Link

### ISSUE THREAD

**Issue by scrabill** [templeman/awesome-ipsum#17]
I clicked Duck Island Greeking Machine since it sounded the most ridiculous, but unfortunately, it turns up with a 404 error. Some quick Googling and it seems like Duck Island Greeking Machine has been defunct for a while. 

Suggestion - Removing the link, incorporating a dead/404 tag, or striking out the link and description

**Comment by templeman** [comment]
Thanks for letting me know @scrabill! I have removed the outdated listing.
