### ISSUE TITLE
Startup Ipsum is down, I think

### ISSUE THREAD

**Issue by scepterdoescode** [templeman/awesome-ipsum#32]
This is another issue request from me, I hope this doesn't bother anyone right now.

Startup Ipsum is probably down. I've checked downfor.io to see if the website's still up, but it says it didn't. I tried using Opera's VPN, but it didn't work still. I don't know if it still works in some other countries, but please let me know if it's still working.

That's all :)
— Ethan

**Comment by templeman** [comment]
Thanks for letting me know @scepterdoescode! I have removed the outdated listing.
