### ISSUE TITLE
A list of (already) deprecated websites or dead links

### ISSUE THREAD

**Issue by pleasedonotdisturb** [templeman/awesome-ipsum#34]
Hello again! I’ve been a long fan of this list of lorem ipsums; which I’ve found a few favorites from here! However, as time goes on, several websites have been archived or deprecated for some reason. I’ve checked all websites using [_Down for Everyone or Just Me?_](https://downfor.io/), and here a list of generators that are already deprecated/dead:

- [Baseball Ipsum](http://baseballipsum.apphb.com/)
- [Borat Ipsum](http://boratipsum.com/), redirects to a bootleg link with some “related searches”
- [Brizzle Ipsum](http://brizzle-ipsum.herokuapp.com/), returns an application error
- [Bullshit Ipsum](http://bullshitipsum.com/), returns a 502 error
- [Dwight K. Ipsum](http://dwightkipsum.com/)
- [Fuck Lorem](http://fucklorem.com/)
- [Game of Thrones Ipsum](http://gameofthronesipsum.richfinelli.com/), although the site’s down, there’s an alternative [CodePen version](https://codepen.io/richfinelli/pen/bpzwQJ) of this website if you’d like to replace that instead
- [Gangsta Lorem Ipsum](http://lorizzle.nl/), aka lorizzle but it’s gone now
- [Hippie Ipsum](http://www.hippieipsum.me/)
- [Liquor Ipsum](http://liquoripsum.com/)
- [Oilers Ipsum](http://www.oilersipsum.com/)
- [Pommy Ipsum](http://www.pommyipsum.com/)
- [Ramen Ipsum](https://ramenipsum.herokuapp.com), application error
- [Riker Ipsum](http://www.rikeripsum.com), application error
- [Skate Ipsum](http://skateipsum.com/)
- [The Vatican Assassin](http://vaticanassass.in/)
- [Trumpem Ipsum](http://trumpemipsum.com/), 404 error, considering that _Donald Trump Ipsum_ already exists

Since all of the lorem ipsums in the Sports and Fitness section are down, I recommend removing the category. Thanks and I hope this message doesn’t bother you too much 😅

**Comment by templeman** [comment]
Thanks for the help @pleasedonotdisturb! I've cleaned up a bunch of dead links using your list as a reference.
