### ISSUE TITLE
T'Lipsum link down

### ISSUE THREAD

**Issue by Jameskmonger** [templeman/awesome-ipsum#7]
The [T'Lipsum link](http://tlipsum.appspot.com/) gives a 404 error.

**Comment by waldyrious** [comment]
For future reference, here's what the site looked like before it went down: http://wayback.archive.org/web/20150514140916id_/http://tlipsum.appspot.com/. If anyone wants to recreate the site, the repo with the code is still around: https://github.com/tonyblundell/tlipsum
